services:
  gateway:
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    restart: unless-stopped
    container_name: tasker-gateway
    env_file: ../.env
    environment:
      AUTH_HOST: auth-service
    expose:
      - "${GATEWAY_PORT}:8080"
    networks:
      - task-engine-network

  auth-service:
    build:
      context: ..
      dockerfile: services/auth/Dockerfile
    restart: unless-stopped
    container_name: tasker-auth-service
    env_file:
      - ../.env
      - ../services/auth/.env
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    depends_on:
      - gateway
      - postgres
      - redis
    expose:
      - "${AUTH_PORT}:50001"
    networks:
      - task-engine-network
