services:
  gateway:
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    restart: unless-stopped
    container_name: tasker-gateway
    env_file: ../.env
    ports:
      - "${GATEWAY_PORT}:8080"

  auth-service:
    build:
      context: ..
      dockerfile: services/auth/Dockerfile
    restart: unless-stopped
    container_name: tasker-auth-service
    env_file:
      - ../.env
      - ../services/auth/.env
    depends_on:
      - gateway
      - postgres
      - redis
    ports:
      - "${AUTH_PORT}:50001"