version: '3'

tasks:
  proto:gen:
    desc: "Generate code from proto files"
    cmds:
      - |
        for file in api/proto/*.proto; do
          name=$(basename "$file" .proto)
          echo "Generating code for $name..."
        
          mkdir -p gen/$name
        
          protoc --proto_path=api/proto \
            --go_out=gen/$name --go_opt=paths=source_relative \
            --go-grpc_out=gen/$name --go-grpc_opt=paths=source_relative \
            "$file"
        done
        echo "Code generation complete."
    silent: false

  docker:infra:dev:
    cmd: docker compose --env-file .env -f deployments/docker-compose.infra.yaml up -d