version: '3'

tasks:
  buf:gen:
    cmds:
      - rm -rf gen/proto
      - task buf:update
      - buf generate

  buf:update:
    cmd: buf dep update

  db:wait:
    cmds:
      - |
        until docker exec tasker-db sh -c 'pg_isready -h 127.0.0.1 -p 5432 -U "$POSTGRES_USER" -d auth_db' >/dev/null 2>&1; do
          echo "waiting for auth db..."
          sleep 1
        done

  db:migrate:auth:
    cmds:
      - task db:wait
      - task -d services/auth migrate:apply

  db:migrate:
    cmds:
      - task db:migrate:auth

  docker:infra:dev:
    cmds:
      - |
        docker compose --env-file .env \
        -f deployments/docker-compose.infra.yaml \
        -f deployments/docker-compose.services.yaml \
        up -d postgres redis kafka

  docker:down:
    cmds:
      - |
        docker compose --env-file .env \
        -f deployments/docker-compose.infra.yaml \
        -f deployments/docker-compose.services.yaml \
        down

  docker:build:
    cmds:
      - |
        docker compose --env-file .env \
        -f deployments/docker-compose.infra.yaml \
        -f deployments/docker-compose.services.yaml \
        build --no-cache

  docker:up:
    cmds:
      - |
        docker compose --env-file .env \
        -f deployments/docker-compose.infra.yaml \
        -f deployments/docker-compose.services.yaml \
        up -d

  run:app:
    cmds:
      - task docker:down

      - task buf:update
      - task buf:gen

      - task docker:infra:dev
      - task db:migrate

      - task docker:build
      - task docker:up
