version: '3'

tasks:
  buf:gen:
    cmds:
      - task buf:update
      - buf generate

  buf:update:
    cmd: buf dep update

  docker:infra:dev:
    cmd: docker compose --env-file .env -f deployments/docker-compose.infra.yaml up -d

  docker:down:
    cmds:
      - |
        docker compose --env-file .env \
        -f deployments/docker-compose.infra.yaml \
        -f deployments/docker-compose.services.yaml \
        down

  run:app:
    cmds:
    - task docker:down
    - task buf:update
    - task buf:gen
    - |
      docker compose --env-file .env \
      -f deployments/docker-compose.infra.yaml \
      -f deployments/docker-compose.services.yaml \
      up -d --build
